image: java:8-jdk

stages:
  - deploy

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

deploy:
   stage: deploy
   image: ubuntu
   before_script:
     - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
     - mkdir -p ~/.ssh
     - eval $(ssh-agent -s)
     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
     - cat ~/.ssh/config
     - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
     - apt-get -y install rsync
     - chmod 700 ~/.ssh/*
   script:
    - echo "test-docker-ci-cd" > ~/README.txt 
    - curl l2gstaging.rrz.uni-hamburg.de

after_script:
  - echo "End CI"