image: java:8-jdk

stages:
  - build
  - deploy

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew clean assemble
  artifacts:
    paths:
      - modules/**/build/libs/*.jar
      - themes/**/dist/*.war
    expire_in: 1 week

deploy:
   stage: deploy
   image: ubuntu
   before_script:
     - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
     - eval $(ssh-agent -s)
     - mkdir -p ~/.ssh
     - chmod 700 ~/.ssh
     - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - ssh-add ~/.ssh/id_rsa
     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   script:
     - scp 'modules/*/build/libs/*.jar' nutzer@l2gstaging.rrz.uni-hamburg.de:/home/nutzer/l2gdeploy-ci-cd
     - scp 'themes/*/dist/*.war' nutzer@l2gstaging.rrz.uni-hamburg.de:/home/nutzer/l2gdeploy-ci-cd
   only:
     - master