/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import de.uhh.l2g.plugins.model.Coordinator;
import de.uhh.l2g.plugins.model.CoordinatorModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Coordinator service. Represents a row in the &quot;LG_Coordinator&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CoordinatorModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CoordinatorImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see CoordinatorImpl
 * @generated
 */
@ProviderType
public class CoordinatorModelImpl
	extends BaseModelImpl<Coordinator> implements CoordinatorModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a coordinator model instance should use the <code>Coordinator</code> interface instead.
	 */
	public static final String TABLE_NAME = "LG_Coordinator";

	public static final Object[][] TABLE_COLUMNS = {
		{"coordinatorId", Types.BIGINT}, {"institutionId", Types.BIGINT},
		{"officeId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("coordinatorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("institutionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("officeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LG_Coordinator (coordinatorId LONG not null primary key,institutionId LONG,officeId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table LG_Coordinator";

	public static final String ORDER_BY_JPQL =
		" ORDER BY coordinator.coordinatorId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LG_Coordinator.coordinatorId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.Coordinator"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.Coordinator"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.de.uhh.l2g.plugins.model.Coordinator"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long INSTITUTIONID_COLUMN_BITMASK = 4L;

	public static final long OFFICEID_COLUMN_BITMASK = 8L;

	public static final long COORDINATORID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"lock.expiration.time.de.uhh.l2g.plugins.model.Coordinator"));

	public CoordinatorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _coordinatorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCoordinatorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _coordinatorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Coordinator.class;
	}

	@Override
	public String getModelClassName() {
		return Coordinator.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Coordinator, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Coordinator, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Coordinator, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Coordinator)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Coordinator, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Coordinator, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Coordinator)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Coordinator, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Coordinator, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Coordinator>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Coordinator.class.getClassLoader(), Coordinator.class,
			ModelWrapper.class);

		try {
			Constructor<Coordinator> constructor =
				(Constructor<Coordinator>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Coordinator, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Coordinator, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Coordinator, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Coordinator, Object>>();
		Map<String, BiConsumer<Coordinator, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Coordinator, ?>>();

		attributeGetterFunctions.put(
			"coordinatorId", Coordinator::getCoordinatorId);
		attributeSetterBiConsumers.put(
			"coordinatorId",
			(BiConsumer<Coordinator, Long>)Coordinator::setCoordinatorId);
		attributeGetterFunctions.put(
			"institutionId", Coordinator::getInstitutionId);
		attributeSetterBiConsumers.put(
			"institutionId",
			(BiConsumer<Coordinator, Long>)Coordinator::setInstitutionId);
		attributeGetterFunctions.put("officeId", Coordinator::getOfficeId);
		attributeSetterBiConsumers.put(
			"officeId",
			(BiConsumer<Coordinator, Long>)Coordinator::setOfficeId);
		attributeGetterFunctions.put("groupId", Coordinator::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Coordinator, Long>)Coordinator::setGroupId);
		attributeGetterFunctions.put("companyId", Coordinator::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<Coordinator, Long>)Coordinator::setCompanyId);
		attributeGetterFunctions.put("userId", Coordinator::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Coordinator, Long>)Coordinator::setUserId);
		attributeGetterFunctions.put("userName", Coordinator::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<Coordinator, String>)Coordinator::setUserName);
		attributeGetterFunctions.put("createDate", Coordinator::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Coordinator, Date>)Coordinator::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Coordinator::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Coordinator, Date>)Coordinator::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getCoordinatorId() {
		return _coordinatorId;
	}

	@Override
	public void setCoordinatorId(long coordinatorId) {
		_coordinatorId = coordinatorId;
	}

	@Override
	public long getInstitutionId() {
		return _institutionId;
	}

	@Override
	public void setInstitutionId(long institutionId) {
		_columnBitmask |= INSTITUTIONID_COLUMN_BITMASK;

		if (!_setOriginalInstitutionId) {
			_setOriginalInstitutionId = true;

			_originalInstitutionId = _institutionId;
		}

		_institutionId = institutionId;
	}

	public long getOriginalInstitutionId() {
		return _originalInstitutionId;
	}

	@Override
	public long getOfficeId() {
		return _officeId;
	}

	@Override
	public void setOfficeId(long officeId) {
		_columnBitmask |= OFFICEID_COLUMN_BITMASK;

		if (!_setOriginalOfficeId) {
			_setOriginalOfficeId = true;

			_originalOfficeId = _officeId;
		}

		_officeId = officeId;
	}

	public long getOriginalOfficeId() {
		return _originalOfficeId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Coordinator.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Coordinator toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Coordinator>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CoordinatorImpl coordinatorImpl = new CoordinatorImpl();

		coordinatorImpl.setCoordinatorId(getCoordinatorId());
		coordinatorImpl.setInstitutionId(getInstitutionId());
		coordinatorImpl.setOfficeId(getOfficeId());
		coordinatorImpl.setGroupId(getGroupId());
		coordinatorImpl.setCompanyId(getCompanyId());
		coordinatorImpl.setUserId(getUserId());
		coordinatorImpl.setUserName(getUserName());
		coordinatorImpl.setCreateDate(getCreateDate());
		coordinatorImpl.setModifiedDate(getModifiedDate());

		coordinatorImpl.resetOriginalValues();

		return coordinatorImpl;
	}

	@Override
	public int compareTo(Coordinator coordinator) {
		long primaryKey = coordinator.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Coordinator)) {
			return false;
		}

		Coordinator coordinator = (Coordinator)obj;

		long primaryKey = coordinator.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CoordinatorModelImpl coordinatorModelImpl = this;

		coordinatorModelImpl._originalInstitutionId =
			coordinatorModelImpl._institutionId;

		coordinatorModelImpl._setOriginalInstitutionId = false;

		coordinatorModelImpl._originalOfficeId = coordinatorModelImpl._officeId;

		coordinatorModelImpl._setOriginalOfficeId = false;

		coordinatorModelImpl._originalGroupId = coordinatorModelImpl._groupId;

		coordinatorModelImpl._setOriginalGroupId = false;

		coordinatorModelImpl._originalCompanyId =
			coordinatorModelImpl._companyId;

		coordinatorModelImpl._setOriginalCompanyId = false;

		coordinatorModelImpl._setModifiedDate = false;

		coordinatorModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Coordinator> toCacheModel() {
		CoordinatorCacheModel coordinatorCacheModel =
			new CoordinatorCacheModel();

		coordinatorCacheModel.coordinatorId = getCoordinatorId();

		coordinatorCacheModel.institutionId = getInstitutionId();

		coordinatorCacheModel.officeId = getOfficeId();

		coordinatorCacheModel.groupId = getGroupId();

		coordinatorCacheModel.companyId = getCompanyId();

		coordinatorCacheModel.userId = getUserId();

		coordinatorCacheModel.userName = getUserName();

		String userName = coordinatorCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			coordinatorCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			coordinatorCacheModel.createDate = createDate.getTime();
		}
		else {
			coordinatorCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			coordinatorCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			coordinatorCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return coordinatorCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Coordinator, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Coordinator, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Coordinator, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Coordinator)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Coordinator, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Coordinator, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Coordinator, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Coordinator)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Coordinator>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _coordinatorId;
	private long _institutionId;
	private long _originalInstitutionId;
	private boolean _setOriginalInstitutionId;
	private long _officeId;
	private long _originalOfficeId;
	private boolean _setOriginalOfficeId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _columnBitmask;
	private Coordinator _escapedModel;

}