/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import de.uhh.l2g.plugins.model.Lastvideolist;
import de.uhh.l2g.plugins.model.LastvideolistModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Lastvideolist service. Represents a row in the &quot;LG_Lastvideolist&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>LastvideolistModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LastvideolistImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see LastvideolistImpl
 * @generated
 */
@ProviderType
public class LastvideolistModelImpl
	extends BaseModelImpl<Lastvideolist> implements LastvideolistModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lastvideolist model instance should use the <code>Lastvideolist</code> interface instead.
	 */
	public static final String TABLE_NAME = "LG_Lastvideolist";

	public static final Object[][] TABLE_COLUMNS = {
		{"lastvideolistId", Types.INTEGER}, {"videoId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("lastvideolistId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("videoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LG_Lastvideolist (lastvideolistId INTEGER not null primary key,videoId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table LG_Lastvideolist";

	public static final String ORDER_BY_JPQL =
		" ORDER BY lastvideolist.lastvideolistId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LG_Lastvideolist.lastvideolistId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.Lastvideolist"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.Lastvideolist"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.de.uhh.l2g.plugins.model.Lastvideolist"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long VIDEOID_COLUMN_BITMASK = 4L;

	public static final long LASTVIDEOLISTID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"lock.expiration.time.de.uhh.l2g.plugins.model.Lastvideolist"));

	public LastvideolistModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _lastvideolistId;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setLastvideolistId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _lastvideolistId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Lastvideolist.class;
	}

	@Override
	public String getModelClassName() {
		return Lastvideolist.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Lastvideolist, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Lastvideolist, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Lastvideolist, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Lastvideolist)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Lastvideolist, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Lastvideolist, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Lastvideolist)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Lastvideolist, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Lastvideolist, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Lastvideolist>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Lastvideolist.class.getClassLoader(), Lastvideolist.class,
			ModelWrapper.class);

		try {
			Constructor<Lastvideolist> constructor =
				(Constructor<Lastvideolist>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Lastvideolist, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Lastvideolist, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Lastvideolist, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Lastvideolist, Object>>();
		Map<String, BiConsumer<Lastvideolist, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Lastvideolist, ?>>();

		attributeGetterFunctions.put(
			"lastvideolistId", Lastvideolist::getLastvideolistId);
		attributeSetterBiConsumers.put(
			"lastvideolistId",
			(BiConsumer<Lastvideolist, Integer>)
				Lastvideolist::setLastvideolistId);
		attributeGetterFunctions.put("videoId", Lastvideolist::getVideoId);
		attributeSetterBiConsumers.put(
			"videoId",
			(BiConsumer<Lastvideolist, Long>)Lastvideolist::setVideoId);
		attributeGetterFunctions.put("groupId", Lastvideolist::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<Lastvideolist, Long>)Lastvideolist::setGroupId);
		attributeGetterFunctions.put("companyId", Lastvideolist::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<Lastvideolist, Long>)Lastvideolist::setCompanyId);
		attributeGetterFunctions.put("userId", Lastvideolist::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<Lastvideolist, Long>)Lastvideolist::setUserId);
		attributeGetterFunctions.put("userName", Lastvideolist::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<Lastvideolist, String>)Lastvideolist::setUserName);
		attributeGetterFunctions.put(
			"createDate", Lastvideolist::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Lastvideolist, Date>)Lastvideolist::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Lastvideolist::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Lastvideolist, Date>)Lastvideolist::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getLastvideolistId() {
		return _lastvideolistId;
	}

	@Override
	public void setLastvideolistId(int lastvideolistId) {
		_lastvideolistId = lastvideolistId;
	}

	@Override
	public long getVideoId() {
		return _videoId;
	}

	@Override
	public void setVideoId(long videoId) {
		_columnBitmask |= VIDEOID_COLUMN_BITMASK;

		if (!_setOriginalVideoId) {
			_setOriginalVideoId = true;

			_originalVideoId = _videoId;
		}

		_videoId = videoId;
	}

	public long getOriginalVideoId() {
		return _originalVideoId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public Lastvideolist toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Lastvideolist>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LastvideolistImpl lastvideolistImpl = new LastvideolistImpl();

		lastvideolistImpl.setLastvideolistId(getLastvideolistId());
		lastvideolistImpl.setVideoId(getVideoId());
		lastvideolistImpl.setGroupId(getGroupId());
		lastvideolistImpl.setCompanyId(getCompanyId());
		lastvideolistImpl.setUserId(getUserId());
		lastvideolistImpl.setUserName(getUserName());
		lastvideolistImpl.setCreateDate(getCreateDate());
		lastvideolistImpl.setModifiedDate(getModifiedDate());

		lastvideolistImpl.resetOriginalValues();

		return lastvideolistImpl;
	}

	@Override
	public int compareTo(Lastvideolist lastvideolist) {
		int primaryKey = lastvideolist.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Lastvideolist)) {
			return false;
		}

		Lastvideolist lastvideolist = (Lastvideolist)obj;

		int primaryKey = lastvideolist.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		LastvideolistModelImpl lastvideolistModelImpl = this;

		lastvideolistModelImpl._originalVideoId =
			lastvideolistModelImpl._videoId;

		lastvideolistModelImpl._setOriginalVideoId = false;

		lastvideolistModelImpl._originalGroupId =
			lastvideolistModelImpl._groupId;

		lastvideolistModelImpl._setOriginalGroupId = false;

		lastvideolistModelImpl._originalCompanyId =
			lastvideolistModelImpl._companyId;

		lastvideolistModelImpl._setOriginalCompanyId = false;

		lastvideolistModelImpl._setModifiedDate = false;

		lastvideolistModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Lastvideolist> toCacheModel() {
		LastvideolistCacheModel lastvideolistCacheModel =
			new LastvideolistCacheModel();

		lastvideolistCacheModel.lastvideolistId = getLastvideolistId();

		lastvideolistCacheModel.videoId = getVideoId();

		lastvideolistCacheModel.groupId = getGroupId();

		lastvideolistCacheModel.companyId = getCompanyId();

		lastvideolistCacheModel.userId = getUserId();

		lastvideolistCacheModel.userName = getUserName();

		String userName = lastvideolistCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			lastvideolistCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			lastvideolistCacheModel.createDate = createDate.getTime();
		}
		else {
			lastvideolistCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			lastvideolistCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			lastvideolistCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return lastvideolistCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Lastvideolist, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Lastvideolist, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Lastvideolist, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Lastvideolist)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Lastvideolist, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Lastvideolist, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Lastvideolist, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Lastvideolist)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Lastvideolist>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private int _lastvideolistId;
	private long _videoId;
	private long _originalVideoId;
	private boolean _setOriginalVideoId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _columnBitmask;
	private Lastvideolist _escapedModel;

}