/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import de.uhh.l2g.plugins.model.Lectureseries_Institution;
import de.uhh.l2g.plugins.model.Lectureseries_InstitutionModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Lectureseries_Institution service. Represents a row in the &quot;LG_Lectureseries_Institution&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>Lectureseries_InstitutionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Lectureseries_InstitutionImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Lectureseries_InstitutionImpl
 * @generated
 */
public class Lectureseries_InstitutionModelImpl
	extends BaseModelImpl<Lectureseries_Institution>
	implements Lectureseries_InstitutionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lectureseries_ institution model instance should use the <code>Lectureseries_Institution</code> interface instead.
	 */
	public static final String TABLE_NAME = "LG_Lectureseries_Institution";

	public static final Object[][] TABLE_COLUMNS = {
		{"lectureseriesInstitutionId", Types.BIGINT},
		{"lectureseriesId", Types.BIGINT}, {"institutionId", Types.BIGINT},
		{"institutionParentId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("lectureseriesInstitutionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lectureseriesId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("institutionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("institutionParentId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LG_Lectureseries_Institution (lectureseriesInstitutionId LONG not null primary key,lectureseriesId LONG,institutionId LONG,institutionParentId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table LG_Lectureseries_Institution";

	public static final String ORDER_BY_JPQL =
		" ORDER BY lectureseries_Institution.lectureseriesInstitutionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LG_Lectureseries_Institution.lectureseriesInstitutionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.Lectureseries_Institution"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.Lectureseries_Institution"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.de.uhh.l2g.plugins.model.Lectureseries_Institution"),
		true);

	public static final long INSTITUTIONID_COLUMN_BITMASK = 1L;

	public static final long INSTITUTIONPARENTID_COLUMN_BITMASK = 2L;

	public static final long LECTURESERIESID_COLUMN_BITMASK = 4L;

	public static final long LECTURESERIESINSTITUTIONID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"lock.expiration.time.de.uhh.l2g.plugins.model.Lectureseries_Institution"));

	public Lectureseries_InstitutionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _lectureseriesInstitutionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLectureseriesInstitutionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _lectureseriesInstitutionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Lectureseries_Institution.class;
	}

	@Override
	public String getModelClassName() {
		return Lectureseries_Institution.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Lectureseries_Institution, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Lectureseries_Institution, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Lectureseries_Institution, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Lectureseries_Institution)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Lectureseries_Institution, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Lectureseries_Institution, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Lectureseries_Institution)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Lectureseries_Institution, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Lectureseries_Institution, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Lectureseries_Institution>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Lectureseries_Institution.class.getClassLoader(),
			Lectureseries_Institution.class, ModelWrapper.class);

		try {
			Constructor<Lectureseries_Institution> constructor =
				(Constructor<Lectureseries_Institution>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map
		<String, Function<Lectureseries_Institution, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<Lectureseries_Institution, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<Lectureseries_Institution, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<Lectureseries_Institution, Object>>();
		Map<String, BiConsumer<Lectureseries_Institution, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<Lectureseries_Institution, ?>>();

		attributeGetterFunctions.put(
			"lectureseriesInstitutionId",
			Lectureseries_Institution::getLectureseriesInstitutionId);
		attributeSetterBiConsumers.put(
			"lectureseriesInstitutionId",
			(BiConsumer<Lectureseries_Institution, Long>)
				Lectureseries_Institution::setLectureseriesInstitutionId);
		attributeGetterFunctions.put(
			"lectureseriesId", Lectureseries_Institution::getLectureseriesId);
		attributeSetterBiConsumers.put(
			"lectureseriesId",
			(BiConsumer<Lectureseries_Institution, Long>)
				Lectureseries_Institution::setLectureseriesId);
		attributeGetterFunctions.put(
			"institutionId", Lectureseries_Institution::getInstitutionId);
		attributeSetterBiConsumers.put(
			"institutionId",
			(BiConsumer<Lectureseries_Institution, Long>)
				Lectureseries_Institution::setInstitutionId);
		attributeGetterFunctions.put(
			"institutionParentId",
			Lectureseries_Institution::getInstitutionParentId);
		attributeSetterBiConsumers.put(
			"institutionParentId",
			(BiConsumer<Lectureseries_Institution, Long>)
				Lectureseries_Institution::setInstitutionParentId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getLectureseriesInstitutionId() {
		return _lectureseriesInstitutionId;
	}

	@Override
	public void setLectureseriesInstitutionId(long lectureseriesInstitutionId) {
		_lectureseriesInstitutionId = lectureseriesInstitutionId;
	}

	@Override
	public long getLectureseriesId() {
		return _lectureseriesId;
	}

	@Override
	public void setLectureseriesId(long lectureseriesId) {
		_columnBitmask |= LECTURESERIESID_COLUMN_BITMASK;

		if (!_setOriginalLectureseriesId) {
			_setOriginalLectureseriesId = true;

			_originalLectureseriesId = _lectureseriesId;
		}

		_lectureseriesId = lectureseriesId;
	}

	public long getOriginalLectureseriesId() {
		return _originalLectureseriesId;
	}

	@Override
	public long getInstitutionId() {
		return _institutionId;
	}

	@Override
	public void setInstitutionId(long institutionId) {
		_columnBitmask |= INSTITUTIONID_COLUMN_BITMASK;

		if (!_setOriginalInstitutionId) {
			_setOriginalInstitutionId = true;

			_originalInstitutionId = _institutionId;
		}

		_institutionId = institutionId;
	}

	public long getOriginalInstitutionId() {
		return _originalInstitutionId;
	}

	@Override
	public long getInstitutionParentId() {
		return _institutionParentId;
	}

	@Override
	public void setInstitutionParentId(long institutionParentId) {
		_columnBitmask |= INSTITUTIONPARENTID_COLUMN_BITMASK;

		if (!_setOriginalInstitutionParentId) {
			_setOriginalInstitutionParentId = true;

			_originalInstitutionParentId = _institutionParentId;
		}

		_institutionParentId = institutionParentId;
	}

	public long getOriginalInstitutionParentId() {
		return _originalInstitutionParentId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Lectureseries_Institution.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Lectureseries_Institution toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Lectureseries_Institution>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Lectureseries_InstitutionImpl lectureseries_InstitutionImpl =
			new Lectureseries_InstitutionImpl();

		lectureseries_InstitutionImpl.setLectureseriesInstitutionId(
			getLectureseriesInstitutionId());
		lectureseries_InstitutionImpl.setLectureseriesId(getLectureseriesId());
		lectureseries_InstitutionImpl.setInstitutionId(getInstitutionId());
		lectureseries_InstitutionImpl.setInstitutionParentId(
			getInstitutionParentId());

		lectureseries_InstitutionImpl.resetOriginalValues();

		return lectureseries_InstitutionImpl;
	}

	@Override
	public int compareTo(Lectureseries_Institution lectureseries_Institution) {
		long primaryKey = lectureseries_Institution.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Lectureseries_Institution)) {
			return false;
		}

		Lectureseries_Institution lectureseries_Institution =
			(Lectureseries_Institution)object;

		long primaryKey = lectureseries_Institution.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		Lectureseries_InstitutionModelImpl lectureseries_InstitutionModelImpl =
			this;

		lectureseries_InstitutionModelImpl._originalLectureseriesId =
			lectureseries_InstitutionModelImpl._lectureseriesId;

		lectureseries_InstitutionModelImpl._setOriginalLectureseriesId = false;

		lectureseries_InstitutionModelImpl._originalInstitutionId =
			lectureseries_InstitutionModelImpl._institutionId;

		lectureseries_InstitutionModelImpl._setOriginalInstitutionId = false;

		lectureseries_InstitutionModelImpl._originalInstitutionParentId =
			lectureseries_InstitutionModelImpl._institutionParentId;

		lectureseries_InstitutionModelImpl._setOriginalInstitutionParentId =
			false;

		lectureseries_InstitutionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Lectureseries_Institution> toCacheModel() {
		Lectureseries_InstitutionCacheModel
			lectureseries_InstitutionCacheModel =
				new Lectureseries_InstitutionCacheModel();

		lectureseries_InstitutionCacheModel.lectureseriesInstitutionId =
			getLectureseriesInstitutionId();

		lectureseries_InstitutionCacheModel.lectureseriesId =
			getLectureseriesId();

		lectureseries_InstitutionCacheModel.institutionId = getInstitutionId();

		lectureseries_InstitutionCacheModel.institutionParentId =
			getInstitutionParentId();

		return lectureseries_InstitutionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Lectureseries_Institution, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Lectureseries_Institution, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Lectureseries_Institution, Object>
				attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((Lectureseries_Institution)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Lectureseries_Institution, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Lectureseries_Institution, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Lectureseries_Institution, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((Lectureseries_Institution)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, Lectureseries_Institution>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _lectureseriesInstitutionId;
	private long _lectureseriesId;
	private long _originalLectureseriesId;
	private boolean _setOriginalLectureseriesId;
	private long _institutionId;
	private long _originalInstitutionId;
	private boolean _setOriginalInstitutionId;
	private long _institutionParentId;
	private long _originalInstitutionParentId;
	private boolean _setOriginalInstitutionParentId;
	private long _columnBitmask;
	private Lectureseries_Institution _escapedModel;

}