/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import de.uhh.l2g.plugins.model.MediaType;
import de.uhh.l2g.plugins.model.MediaTypeModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MediaType service. Represents a row in the &quot;LG_MediaType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MediaTypeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MediaTypeImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see MediaTypeImpl
 * @generated
 */
public class MediaTypeModelImpl
	extends BaseModelImpl<MediaType> implements MediaTypeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a media type model instance should use the <code>MediaType</code> interface instead.
	 */
	public static final String TABLE_NAME = "LG_MediaType";

	public static final Object[][] TABLE_COLUMNS = {
		{"mediaTypeId", Types.BIGINT}, {"mediaTypeName", Types.VARCHAR},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mediaTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("mediaTypeName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LG_MediaType (mediaTypeId LONG not null primary key,mediaTypeName VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table LG_MediaType";

	public static final String ORDER_BY_JPQL =
		" ORDER BY mediaType.mediaTypeName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LG_MediaType.mediaTypeName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.MediaType"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.MediaType"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.de.uhh.l2g.plugins.model.MediaType"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long MEDIATYPENAME_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"lock.expiration.time.de.uhh.l2g.plugins.model.MediaType"));

	public MediaTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _mediaTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMediaTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _mediaTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MediaType.class;
	}

	@Override
	public String getModelClassName() {
		return MediaType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MediaType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MediaType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MediaType, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((MediaType)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MediaType, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MediaType, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MediaType)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MediaType, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MediaType, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, MediaType>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			MediaType.class.getClassLoader(), MediaType.class,
			ModelWrapper.class);

		try {
			Constructor<MediaType> constructor =
				(Constructor<MediaType>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<MediaType, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MediaType, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MediaType, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MediaType, Object>>();
		Map<String, BiConsumer<MediaType, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MediaType, ?>>();

		attributeGetterFunctions.put("mediaTypeId", MediaType::getMediaTypeId);
		attributeSetterBiConsumers.put(
			"mediaTypeId",
			(BiConsumer<MediaType, Long>)MediaType::setMediaTypeId);
		attributeGetterFunctions.put(
			"mediaTypeName", MediaType::getMediaTypeName);
		attributeSetterBiConsumers.put(
			"mediaTypeName",
			(BiConsumer<MediaType, String>)MediaType::setMediaTypeName);
		attributeGetterFunctions.put("groupId", MediaType::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<MediaType, Long>)MediaType::setGroupId);
		attributeGetterFunctions.put("companyId", MediaType::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<MediaType, Long>)MediaType::setCompanyId);
		attributeGetterFunctions.put("userId", MediaType::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<MediaType, Long>)MediaType::setUserId);
		attributeGetterFunctions.put("userName", MediaType::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<MediaType, String>)MediaType::setUserName);
		attributeGetterFunctions.put("createDate", MediaType::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<MediaType, Date>)MediaType::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", MediaType::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MediaType, Date>)MediaType::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMediaTypeId() {
		return _mediaTypeId;
	}

	@Override
	public void setMediaTypeId(long mediaTypeId) {
		_mediaTypeId = mediaTypeId;
	}

	@Override
	public String getMediaTypeName() {
		if (_mediaTypeName == null) {
			return "";
		}
		else {
			return _mediaTypeName;
		}
	}

	@Override
	public void setMediaTypeName(String mediaTypeName) {
		_columnBitmask = -1L;

		_mediaTypeName = mediaTypeName;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MediaType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MediaType toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MediaType>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MediaTypeImpl mediaTypeImpl = new MediaTypeImpl();

		mediaTypeImpl.setMediaTypeId(getMediaTypeId());
		mediaTypeImpl.setMediaTypeName(getMediaTypeName());
		mediaTypeImpl.setGroupId(getGroupId());
		mediaTypeImpl.setCompanyId(getCompanyId());
		mediaTypeImpl.setUserId(getUserId());
		mediaTypeImpl.setUserName(getUserName());
		mediaTypeImpl.setCreateDate(getCreateDate());
		mediaTypeImpl.setModifiedDate(getModifiedDate());

		mediaTypeImpl.resetOriginalValues();

		return mediaTypeImpl;
	}

	@Override
	public int compareTo(MediaType mediaType) {
		int value = 0;

		value = getMediaTypeName().compareTo(mediaType.getMediaTypeName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MediaType)) {
			return false;
		}

		MediaType mediaType = (MediaType)object;

		long primaryKey = mediaType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MediaTypeModelImpl mediaTypeModelImpl = this;

		mediaTypeModelImpl._originalGroupId = mediaTypeModelImpl._groupId;

		mediaTypeModelImpl._setOriginalGroupId = false;

		mediaTypeModelImpl._originalCompanyId = mediaTypeModelImpl._companyId;

		mediaTypeModelImpl._setOriginalCompanyId = false;

		mediaTypeModelImpl._setModifiedDate = false;

		mediaTypeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MediaType> toCacheModel() {
		MediaTypeCacheModel mediaTypeCacheModel = new MediaTypeCacheModel();

		mediaTypeCacheModel.mediaTypeId = getMediaTypeId();

		mediaTypeCacheModel.mediaTypeName = getMediaTypeName();

		String mediaTypeName = mediaTypeCacheModel.mediaTypeName;

		if ((mediaTypeName != null) && (mediaTypeName.length() == 0)) {
			mediaTypeCacheModel.mediaTypeName = null;
		}

		mediaTypeCacheModel.groupId = getGroupId();

		mediaTypeCacheModel.companyId = getCompanyId();

		mediaTypeCacheModel.userId = getUserId();

		mediaTypeCacheModel.userName = getUserName();

		String userName = mediaTypeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			mediaTypeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			mediaTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			mediaTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			mediaTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			mediaTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return mediaTypeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MediaType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MediaType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MediaType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((MediaType)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MediaType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MediaType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MediaType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MediaType)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MediaType>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mediaTypeId;
	private String _mediaTypeName;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _columnBitmask;
	private MediaType _escapedModel;

}