/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import de.uhh.l2g.plugins.model.OaiRecord_OaiSet;
import de.uhh.l2g.plugins.model.OaiRecord_OaiSetModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the OaiRecord_OaiSet service. Represents a row in the &quot;LG_OaiRecord_OaiSet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OaiRecord_OaiSetModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OaiRecord_OaiSetImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see OaiRecord_OaiSetImpl
 * @generated
 */
public class OaiRecord_OaiSetModelImpl
	extends BaseModelImpl<OaiRecord_OaiSet> implements OaiRecord_OaiSetModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a oai record_ oai set model instance should use the <code>OaiRecord_OaiSet</code> interface instead.
	 */
	public static final String TABLE_NAME = "LG_OaiRecord_OaiSet";

	public static final Object[][] TABLE_COLUMNS = {
		{"oaiRecordOaiSetId", Types.BIGINT}, {"oaiRecordId", Types.BIGINT},
		{"oaiSetId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("oaiRecordOaiSetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("oaiRecordId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("oaiSetId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LG_OaiRecord_OaiSet (oaiRecordOaiSetId LONG not null primary key,oaiRecordId LONG,oaiSetId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table LG_OaiRecord_OaiSet";

	public static final String ORDER_BY_JPQL =
		" ORDER BY oaiRecord_OaiSet.oaiRecordOaiSetId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LG_OaiRecord_OaiSet.oaiRecordOaiSetId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.OaiRecord_OaiSet"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.OaiRecord_OaiSet"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.de.uhh.l2g.plugins.model.OaiRecord_OaiSet"),
		true);

	public static final long OAIRECORDID_COLUMN_BITMASK = 1L;

	public static final long OAISETID_COLUMN_BITMASK = 2L;

	public static final long OAIRECORDOAISETID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"lock.expiration.time.de.uhh.l2g.plugins.model.OaiRecord_OaiSet"));

	public OaiRecord_OaiSetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _oaiRecordOaiSetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOaiRecordOaiSetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _oaiRecordOaiSetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OaiRecord_OaiSet.class;
	}

	@Override
	public String getModelClassName() {
		return OaiRecord_OaiSet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OaiRecord_OaiSet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OaiRecord_OaiSet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OaiRecord_OaiSet, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((OaiRecord_OaiSet)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OaiRecord_OaiSet, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OaiRecord_OaiSet, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(OaiRecord_OaiSet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OaiRecord_OaiSet, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OaiRecord_OaiSet, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, OaiRecord_OaiSet>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			OaiRecord_OaiSet.class.getClassLoader(), OaiRecord_OaiSet.class,
			ModelWrapper.class);

		try {
			Constructor<OaiRecord_OaiSet> constructor =
				(Constructor<OaiRecord_OaiSet>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<OaiRecord_OaiSet, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<OaiRecord_OaiSet, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<OaiRecord_OaiSet, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<OaiRecord_OaiSet, Object>>();
		Map<String, BiConsumer<OaiRecord_OaiSet, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<OaiRecord_OaiSet, ?>>();

		attributeGetterFunctions.put(
			"oaiRecordOaiSetId", OaiRecord_OaiSet::getOaiRecordOaiSetId);
		attributeSetterBiConsumers.put(
			"oaiRecordOaiSetId",
			(BiConsumer<OaiRecord_OaiSet, Long>)
				OaiRecord_OaiSet::setOaiRecordOaiSetId);
		attributeGetterFunctions.put(
			"oaiRecordId", OaiRecord_OaiSet::getOaiRecordId);
		attributeSetterBiConsumers.put(
			"oaiRecordId",
			(BiConsumer<OaiRecord_OaiSet, Long>)
				OaiRecord_OaiSet::setOaiRecordId);
		attributeGetterFunctions.put("oaiSetId", OaiRecord_OaiSet::getOaiSetId);
		attributeSetterBiConsumers.put(
			"oaiSetId",
			(BiConsumer<OaiRecord_OaiSet, Long>)OaiRecord_OaiSet::setOaiSetId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getOaiRecordOaiSetId() {
		return _oaiRecordOaiSetId;
	}

	@Override
	public void setOaiRecordOaiSetId(long oaiRecordOaiSetId) {
		_oaiRecordOaiSetId = oaiRecordOaiSetId;
	}

	@Override
	public long getOaiRecordId() {
		return _oaiRecordId;
	}

	@Override
	public void setOaiRecordId(long oaiRecordId) {
		_columnBitmask |= OAIRECORDID_COLUMN_BITMASK;

		if (!_setOriginalOaiRecordId) {
			_setOriginalOaiRecordId = true;

			_originalOaiRecordId = _oaiRecordId;
		}

		_oaiRecordId = oaiRecordId;
	}

	public long getOriginalOaiRecordId() {
		return _originalOaiRecordId;
	}

	@Override
	public long getOaiSetId() {
		return _oaiSetId;
	}

	@Override
	public void setOaiSetId(long oaiSetId) {
		_columnBitmask |= OAISETID_COLUMN_BITMASK;

		if (!_setOriginalOaiSetId) {
			_setOriginalOaiSetId = true;

			_originalOaiSetId = _oaiSetId;
		}

		_oaiSetId = oaiSetId;
	}

	public long getOriginalOaiSetId() {
		return _originalOaiSetId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, OaiRecord_OaiSet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OaiRecord_OaiSet toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OaiRecord_OaiSet>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OaiRecord_OaiSetImpl oaiRecord_OaiSetImpl = new OaiRecord_OaiSetImpl();

		oaiRecord_OaiSetImpl.setOaiRecordOaiSetId(getOaiRecordOaiSetId());
		oaiRecord_OaiSetImpl.setOaiRecordId(getOaiRecordId());
		oaiRecord_OaiSetImpl.setOaiSetId(getOaiSetId());

		oaiRecord_OaiSetImpl.resetOriginalValues();

		return oaiRecord_OaiSetImpl;
	}

	@Override
	public int compareTo(OaiRecord_OaiSet oaiRecord_OaiSet) {
		long primaryKey = oaiRecord_OaiSet.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof OaiRecord_OaiSet)) {
			return false;
		}

		OaiRecord_OaiSet oaiRecord_OaiSet = (OaiRecord_OaiSet)object;

		long primaryKey = oaiRecord_OaiSet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		OaiRecord_OaiSetModelImpl oaiRecord_OaiSetModelImpl = this;

		oaiRecord_OaiSetModelImpl._originalOaiRecordId =
			oaiRecord_OaiSetModelImpl._oaiRecordId;

		oaiRecord_OaiSetModelImpl._setOriginalOaiRecordId = false;

		oaiRecord_OaiSetModelImpl._originalOaiSetId =
			oaiRecord_OaiSetModelImpl._oaiSetId;

		oaiRecord_OaiSetModelImpl._setOriginalOaiSetId = false;

		oaiRecord_OaiSetModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<OaiRecord_OaiSet> toCacheModel() {
		OaiRecord_OaiSetCacheModel oaiRecord_OaiSetCacheModel =
			new OaiRecord_OaiSetCacheModel();

		oaiRecord_OaiSetCacheModel.oaiRecordOaiSetId = getOaiRecordOaiSetId();

		oaiRecord_OaiSetCacheModel.oaiRecordId = getOaiRecordId();

		oaiRecord_OaiSetCacheModel.oaiSetId = getOaiSetId();

		return oaiRecord_OaiSetCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OaiRecord_OaiSet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OaiRecord_OaiSet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OaiRecord_OaiSet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((OaiRecord_OaiSet)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<OaiRecord_OaiSet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<OaiRecord_OaiSet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OaiRecord_OaiSet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((OaiRecord_OaiSet)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, OaiRecord_OaiSet>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _oaiRecordOaiSetId;
	private long _oaiRecordId;
	private long _originalOaiRecordId;
	private boolean _setOriginalOaiRecordId;
	private long _oaiSetId;
	private long _originalOaiSetId;
	private boolean _setOriginalOaiSetId;
	private long _columnBitmask;
	private OaiRecord_OaiSet _escapedModel;

}