/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import de.uhh.l2g.plugins.model.OaiRecord;
import de.uhh.l2g.plugins.model.OaiRecordModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the OaiRecord service. Represents a row in the &quot;LG_OaiRecord&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OaiRecordModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OaiRecordImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see OaiRecordImpl
 * @generated
 */
public class OaiRecordModelImpl
	extends BaseModelImpl<OaiRecord> implements OaiRecordModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a oai record model instance should use the <code>OaiRecord</code> interface instead.
	 */
	public static final String TABLE_NAME = "LG_OaiRecord";

	public static final Object[][] TABLE_COLUMNS = {
		{"oaiRecordId", Types.BIGINT}, {"videoId", Types.BIGINT},
		{"identifier", Types.VARCHAR}, {"datestamp", Types.TIMESTAMP},
		{"deleted", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("oaiRecordId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("videoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("identifier", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("datestamp", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("deleted", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LG_OaiRecord (oaiRecordId LONG not null primary key,videoId LONG,identifier VARCHAR(75) null,datestamp DATE null,deleted BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table LG_OaiRecord";

	public static final String ORDER_BY_JPQL =
		" ORDER BY oaiRecord.datestamp DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LG_OaiRecord.datestamp DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.OaiRecord"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.OaiRecord"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.de.uhh.l2g.plugins.model.OaiRecord"),
		true);

	public static final long IDENTIFIER_COLUMN_BITMASK = 1L;

	public static final long VIDEOID_COLUMN_BITMASK = 2L;

	public static final long DATESTAMP_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"lock.expiration.time.de.uhh.l2g.plugins.model.OaiRecord"));

	public OaiRecordModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _oaiRecordId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOaiRecordId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _oaiRecordId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OaiRecord.class;
	}

	@Override
	public String getModelClassName() {
		return OaiRecord.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OaiRecord, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OaiRecord, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OaiRecord, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((OaiRecord)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OaiRecord, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OaiRecord, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(OaiRecord)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OaiRecord, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OaiRecord, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, OaiRecord>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			OaiRecord.class.getClassLoader(), OaiRecord.class,
			ModelWrapper.class);

		try {
			Constructor<OaiRecord> constructor =
				(Constructor<OaiRecord>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<OaiRecord, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<OaiRecord, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<OaiRecord, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<OaiRecord, Object>>();
		Map<String, BiConsumer<OaiRecord, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<OaiRecord, ?>>();

		attributeGetterFunctions.put("oaiRecordId", OaiRecord::getOaiRecordId);
		attributeSetterBiConsumers.put(
			"oaiRecordId",
			(BiConsumer<OaiRecord, Long>)OaiRecord::setOaiRecordId);
		attributeGetterFunctions.put("videoId", OaiRecord::getVideoId);
		attributeSetterBiConsumers.put(
			"videoId", (BiConsumer<OaiRecord, Long>)OaiRecord::setVideoId);
		attributeGetterFunctions.put("identifier", OaiRecord::getIdentifier);
		attributeSetterBiConsumers.put(
			"identifier",
			(BiConsumer<OaiRecord, String>)OaiRecord::setIdentifier);
		attributeGetterFunctions.put("datestamp", OaiRecord::getDatestamp);
		attributeSetterBiConsumers.put(
			"datestamp", (BiConsumer<OaiRecord, Date>)OaiRecord::setDatestamp);
		attributeGetterFunctions.put("deleted", OaiRecord::getDeleted);
		attributeSetterBiConsumers.put(
			"deleted", (BiConsumer<OaiRecord, Boolean>)OaiRecord::setDeleted);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getOaiRecordId() {
		return _oaiRecordId;
	}

	@Override
	public void setOaiRecordId(long oaiRecordId) {
		_oaiRecordId = oaiRecordId;
	}

	@Override
	public long getVideoId() {
		return _videoId;
	}

	@Override
	public void setVideoId(long videoId) {
		_columnBitmask |= VIDEOID_COLUMN_BITMASK;

		if (!_setOriginalVideoId) {
			_setOriginalVideoId = true;

			_originalVideoId = _videoId;
		}

		_videoId = videoId;
	}

	public long getOriginalVideoId() {
		return _originalVideoId;
	}

	@Override
	public String getIdentifier() {
		if (_identifier == null) {
			return "";
		}
		else {
			return _identifier;
		}
	}

	@Override
	public void setIdentifier(String identifier) {
		_columnBitmask |= IDENTIFIER_COLUMN_BITMASK;

		if (_originalIdentifier == null) {
			_originalIdentifier = _identifier;
		}

		_identifier = identifier;
	}

	public String getOriginalIdentifier() {
		return GetterUtil.getString(_originalIdentifier);
	}

	@Override
	public Date getDatestamp() {
		return _datestamp;
	}

	@Override
	public void setDatestamp(Date datestamp) {
		_columnBitmask = -1L;

		_datestamp = datestamp;
	}

	@Override
	public boolean getDeleted() {
		return _deleted;
	}

	@Override
	public boolean isDeleted() {
		return _deleted;
	}

	@Override
	public void setDeleted(boolean deleted) {
		_deleted = deleted;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, OaiRecord.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OaiRecord toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OaiRecord>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OaiRecordImpl oaiRecordImpl = new OaiRecordImpl();

		oaiRecordImpl.setOaiRecordId(getOaiRecordId());
		oaiRecordImpl.setVideoId(getVideoId());
		oaiRecordImpl.setIdentifier(getIdentifier());
		oaiRecordImpl.setDatestamp(getDatestamp());
		oaiRecordImpl.setDeleted(isDeleted());

		oaiRecordImpl.resetOriginalValues();

		return oaiRecordImpl;
	}

	@Override
	public int compareTo(OaiRecord oaiRecord) {
		int value = 0;

		value = DateUtil.compareTo(getDatestamp(), oaiRecord.getDatestamp());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof OaiRecord)) {
			return false;
		}

		OaiRecord oaiRecord = (OaiRecord)object;

		long primaryKey = oaiRecord.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		OaiRecordModelImpl oaiRecordModelImpl = this;

		oaiRecordModelImpl._originalVideoId = oaiRecordModelImpl._videoId;

		oaiRecordModelImpl._setOriginalVideoId = false;

		oaiRecordModelImpl._originalIdentifier = oaiRecordModelImpl._identifier;

		oaiRecordModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<OaiRecord> toCacheModel() {
		OaiRecordCacheModel oaiRecordCacheModel = new OaiRecordCacheModel();

		oaiRecordCacheModel.oaiRecordId = getOaiRecordId();

		oaiRecordCacheModel.videoId = getVideoId();

		oaiRecordCacheModel.identifier = getIdentifier();

		String identifier = oaiRecordCacheModel.identifier;

		if ((identifier != null) && (identifier.length() == 0)) {
			oaiRecordCacheModel.identifier = null;
		}

		Date datestamp = getDatestamp();

		if (datestamp != null) {
			oaiRecordCacheModel.datestamp = datestamp.getTime();
		}
		else {
			oaiRecordCacheModel.datestamp = Long.MIN_VALUE;
		}

		oaiRecordCacheModel.deleted = isDeleted();

		return oaiRecordCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OaiRecord, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OaiRecord, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OaiRecord, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((OaiRecord)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<OaiRecord, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<OaiRecord, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OaiRecord, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((OaiRecord)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, OaiRecord>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _oaiRecordId;
	private long _videoId;
	private long _originalVideoId;
	private boolean _setOriginalVideoId;
	private String _identifier;
	private String _originalIdentifier;
	private Date _datestamp;
	private boolean _deleted;
	private long _columnBitmask;
	private OaiRecord _escapedModel;

}