/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import de.uhh.l2g.plugins.model.OaiSet;
import de.uhh.l2g.plugins.model.OaiSetModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the OaiSet service. Represents a row in the &quot;LG_OaiSet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OaiSetModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OaiSetImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see OaiSetImpl
 * @generated
 */
public class OaiSetModelImpl
	extends BaseModelImpl<OaiSet> implements OaiSetModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a oai set model instance should use the <code>OaiSet</code> interface instead.
	 */
	public static final String TABLE_NAME = "LG_OaiSet";

	public static final Object[][] TABLE_COLUMNS = {
		{"oaiSetId", Types.BIGINT}, {"setSpec", Types.VARCHAR},
		{"setName", Types.VARCHAR}, {"setDescription", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("oaiSetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("setSpec", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("setName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("setDescription", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LG_OaiSet (oaiSetId LONG not null primary key,setSpec VARCHAR(75) null,setName VARCHAR(75) null,setDescription VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table LG_OaiSet";

	public static final String ORDER_BY_JPQL = " ORDER BY oaiSet.oaiSetId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LG_OaiSet.oaiSetId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.OaiSet"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.OaiSet"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"lock.expiration.time.de.uhh.l2g.plugins.model.OaiSet"));

	public OaiSetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _oaiSetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOaiSetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _oaiSetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OaiSet.class;
	}

	@Override
	public String getModelClassName() {
		return OaiSet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OaiSet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OaiSet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OaiSet, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((OaiSet)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OaiSet, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OaiSet, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(OaiSet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OaiSet, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OaiSet, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, OaiSet>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			OaiSet.class.getClassLoader(), OaiSet.class, ModelWrapper.class);

		try {
			Constructor<OaiSet> constructor =
				(Constructor<OaiSet>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<OaiSet, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<OaiSet, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<OaiSet, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<OaiSet, Object>>();
		Map<String, BiConsumer<OaiSet, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<OaiSet, ?>>();

		attributeGetterFunctions.put("oaiSetId", OaiSet::getOaiSetId);
		attributeSetterBiConsumers.put(
			"oaiSetId", (BiConsumer<OaiSet, Long>)OaiSet::setOaiSetId);
		attributeGetterFunctions.put("setSpec", OaiSet::getSetSpec);
		attributeSetterBiConsumers.put(
			"setSpec", (BiConsumer<OaiSet, String>)OaiSet::setSetSpec);
		attributeGetterFunctions.put("setName", OaiSet::getSetName);
		attributeSetterBiConsumers.put(
			"setName", (BiConsumer<OaiSet, String>)OaiSet::setSetName);
		attributeGetterFunctions.put(
			"setDescription", OaiSet::getSetDescription);
		attributeSetterBiConsumers.put(
			"setDescription",
			(BiConsumer<OaiSet, String>)OaiSet::setSetDescription);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getOaiSetId() {
		return _oaiSetId;
	}

	@Override
	public void setOaiSetId(long oaiSetId) {
		_oaiSetId = oaiSetId;
	}

	@Override
	public String getSetSpec() {
		if (_setSpec == null) {
			return "";
		}
		else {
			return _setSpec;
		}
	}

	@Override
	public void setSetSpec(String setSpec) {
		_setSpec = setSpec;
	}

	@Override
	public String getSetName() {
		if (_setName == null) {
			return "";
		}
		else {
			return _setName;
		}
	}

	@Override
	public void setSetName(String setName) {
		_setName = setName;
	}

	@Override
	public String getSetDescription() {
		if (_setDescription == null) {
			return "";
		}
		else {
			return _setDescription;
		}
	}

	@Override
	public void setSetDescription(String setDescription) {
		_setDescription = setDescription;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, OaiSet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OaiSet toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OaiSet>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OaiSetImpl oaiSetImpl = new OaiSetImpl();

		oaiSetImpl.setOaiSetId(getOaiSetId());
		oaiSetImpl.setSetSpec(getSetSpec());
		oaiSetImpl.setSetName(getSetName());
		oaiSetImpl.setSetDescription(getSetDescription());

		oaiSetImpl.resetOriginalValues();

		return oaiSetImpl;
	}

	@Override
	public int compareTo(OaiSet oaiSet) {
		long primaryKey = oaiSet.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof OaiSet)) {
			return false;
		}

		OaiSet oaiSet = (OaiSet)object;

		long primaryKey = oaiSet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<OaiSet> toCacheModel() {
		OaiSetCacheModel oaiSetCacheModel = new OaiSetCacheModel();

		oaiSetCacheModel.oaiSetId = getOaiSetId();

		oaiSetCacheModel.setSpec = getSetSpec();

		String setSpec = oaiSetCacheModel.setSpec;

		if ((setSpec != null) && (setSpec.length() == 0)) {
			oaiSetCacheModel.setSpec = null;
		}

		oaiSetCacheModel.setName = getSetName();

		String setName = oaiSetCacheModel.setName;

		if ((setName != null) && (setName.length() == 0)) {
			oaiSetCacheModel.setName = null;
		}

		oaiSetCacheModel.setDescription = getSetDescription();

		String setDescription = oaiSetCacheModel.setDescription;

		if ((setDescription != null) && (setDescription.length() == 0)) {
			oaiSetCacheModel.setDescription = null;
		}

		return oaiSetCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OaiSet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OaiSet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OaiSet, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((OaiSet)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<OaiSet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<OaiSet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OaiSet, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((OaiSet)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, OaiSet>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _oaiSetId;
	private String _setSpec;
	private String _setName;
	private String _setDescription;
	private OaiSet _escapedModel;

}