/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import de.uhh.l2g.plugins.model.Producer_Lectureseries;
import de.uhh.l2g.plugins.service.Producer_LectureseriesLocalServiceUtil;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The extended model base implementation for the Producer_Lectureseries service. Represents a row in the &quot;LG_Producer_Lectureseries&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Producer_LectureseriesImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Producer_LectureseriesImpl
 * @see Producer_Lectureseries
 * @generated
 */
@ProviderType
public abstract class Producer_LectureseriesBaseImpl
	extends Producer_LectureseriesModelImpl implements Producer_Lectureseries {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a producer_ lectureseries model instance should use the <code>Producer_Lectureseries</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Producer_LectureseriesLocalServiceUtil.addProducer_Lectureseries(
				this);
		}
		else {
			Producer_LectureseriesLocalServiceUtil.updateProducer_Lectureseries(
				this);
		}
	}

}