/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import de.uhh.l2g.plugins.model.Term;
import de.uhh.l2g.plugins.model.TermModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Term service. Represents a row in the &quot;LG_Term&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TermModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TermImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see TermImpl
 * @generated
 */
public class TermModelImpl extends BaseModelImpl<Term> implements TermModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a term model instance should use the <code>Term</code> interface instead.
	 */
	public static final String TABLE_NAME = "LG_Term";

	public static final Object[][] TABLE_COLUMNS = {
		{"termId", Types.BIGINT}, {"parentId", Types.BIGINT},
		{"languageId", Types.VARCHAR}, {"prefix", Types.VARCHAR},
		{"year", Types.VARCHAR}, {"translation", Types.VARCHAR},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("termId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("languageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("prefix", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("year", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("translation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LG_Term (termId LONG not null primary key,parentId LONG,languageId VARCHAR(75) null,prefix VARCHAR(75) null,year VARCHAR(75) null,translation VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table LG_Term";

	public static final String ORDER_BY_JPQL = " ORDER BY term.year DESC";

	public static final String ORDER_BY_SQL = " ORDER BY LG_Term.year DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.Term"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.Term"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.de.uhh.l2g.plugins.model.Term"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long PREFIX_COLUMN_BITMASK = 4L;

	public static final long YEAR_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"lock.expiration.time.de.uhh.l2g.plugins.model.Term"));

	public TermModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _termId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTermId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _termId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Term.class;
	}

	@Override
	public String getModelClassName() {
		return Term.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Term, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Term, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Term, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Term)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Term, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Term, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Term)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Term, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Term, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Term>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Term.class.getClassLoader(), Term.class, ModelWrapper.class);

		try {
			Constructor<Term> constructor =
				(Constructor<Term>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Term, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Term, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Term, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Term, Object>>();
		Map<String, BiConsumer<Term, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Term, ?>>();

		attributeGetterFunctions.put("termId", Term::getTermId);
		attributeSetterBiConsumers.put(
			"termId", (BiConsumer<Term, Long>)Term::setTermId);
		attributeGetterFunctions.put("parentId", Term::getParentId);
		attributeSetterBiConsumers.put(
			"parentId", (BiConsumer<Term, Long>)Term::setParentId);
		attributeGetterFunctions.put("languageId", Term::getLanguageId);
		attributeSetterBiConsumers.put(
			"languageId", (BiConsumer<Term, String>)Term::setLanguageId);
		attributeGetterFunctions.put("prefix", Term::getPrefix);
		attributeSetterBiConsumers.put(
			"prefix", (BiConsumer<Term, String>)Term::setPrefix);
		attributeGetterFunctions.put("year", Term::getYear);
		attributeSetterBiConsumers.put(
			"year", (BiConsumer<Term, String>)Term::setYear);
		attributeGetterFunctions.put("translation", Term::getTranslation);
		attributeSetterBiConsumers.put(
			"translation", (BiConsumer<Term, String>)Term::setTranslation);
		attributeGetterFunctions.put("groupId", Term::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Term, Long>)Term::setGroupId);
		attributeGetterFunctions.put("companyId", Term::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Term, Long>)Term::setCompanyId);
		attributeGetterFunctions.put("userId", Term::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Term, Long>)Term::setUserId);
		attributeGetterFunctions.put("userName", Term::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Term, String>)Term::setUserName);
		attributeGetterFunctions.put("createDate", Term::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Term, Date>)Term::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Term::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Term, Date>)Term::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getTermId() {
		return _termId;
	}

	@Override
	public void setTermId(long termId) {
		_termId = termId;
	}

	@Override
	public long getParentId() {
		return _parentId;
	}

	@Override
	public void setParentId(long parentId) {
		_parentId = parentId;
	}

	@Override
	public String getLanguageId() {
		if (_languageId == null) {
			return "";
		}
		else {
			return _languageId;
		}
	}

	@Override
	public void setLanguageId(String languageId) {
		_languageId = languageId;
	}

	@Override
	public String getPrefix() {
		if (_prefix == null) {
			return "";
		}
		else {
			return _prefix;
		}
	}

	@Override
	public void setPrefix(String prefix) {
		_columnBitmask |= PREFIX_COLUMN_BITMASK;

		if (_originalPrefix == null) {
			_originalPrefix = _prefix;
		}

		_prefix = prefix;
	}

	public String getOriginalPrefix() {
		return GetterUtil.getString(_originalPrefix);
	}

	@Override
	public String getYear() {
		if (_year == null) {
			return "";
		}
		else {
			return _year;
		}
	}

	@Override
	public void setYear(String year) {
		_columnBitmask = -1L;

		if (_originalYear == null) {
			_originalYear = _year;
		}

		_year = year;
	}

	public String getOriginalYear() {
		return GetterUtil.getString(_originalYear);
	}

	@Override
	public String getTranslation() {
		if (_translation == null) {
			return "";
		}
		else {
			return _translation;
		}
	}

	@Override
	public void setTranslation(String translation) {
		_translation = translation;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Term.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Term toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Term>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TermImpl termImpl = new TermImpl();

		termImpl.setTermId(getTermId());
		termImpl.setParentId(getParentId());
		termImpl.setLanguageId(getLanguageId());
		termImpl.setPrefix(getPrefix());
		termImpl.setYear(getYear());
		termImpl.setTranslation(getTranslation());
		termImpl.setGroupId(getGroupId());
		termImpl.setCompanyId(getCompanyId());
		termImpl.setUserId(getUserId());
		termImpl.setUserName(getUserName());
		termImpl.setCreateDate(getCreateDate());
		termImpl.setModifiedDate(getModifiedDate());

		termImpl.resetOriginalValues();

		return termImpl;
	}

	@Override
	public int compareTo(Term term) {
		int value = 0;

		value = getYear().compareTo(term.getYear());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Term)) {
			return false;
		}

		Term term = (Term)object;

		long primaryKey = term.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TermModelImpl termModelImpl = this;

		termModelImpl._originalPrefix = termModelImpl._prefix;

		termModelImpl._originalYear = termModelImpl._year;

		termModelImpl._originalGroupId = termModelImpl._groupId;

		termModelImpl._setOriginalGroupId = false;

		termModelImpl._originalCompanyId = termModelImpl._companyId;

		termModelImpl._setOriginalCompanyId = false;

		termModelImpl._setModifiedDate = false;

		termModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Term> toCacheModel() {
		TermCacheModel termCacheModel = new TermCacheModel();

		termCacheModel.termId = getTermId();

		termCacheModel.parentId = getParentId();

		termCacheModel.languageId = getLanguageId();

		String languageId = termCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			termCacheModel.languageId = null;
		}

		termCacheModel.prefix = getPrefix();

		String prefix = termCacheModel.prefix;

		if ((prefix != null) && (prefix.length() == 0)) {
			termCacheModel.prefix = null;
		}

		termCacheModel.year = getYear();

		String year = termCacheModel.year;

		if ((year != null) && (year.length() == 0)) {
			termCacheModel.year = null;
		}

		termCacheModel.translation = getTranslation();

		String translation = termCacheModel.translation;

		if ((translation != null) && (translation.length() == 0)) {
			termCacheModel.translation = null;
		}

		termCacheModel.groupId = getGroupId();

		termCacheModel.companyId = getCompanyId();

		termCacheModel.userId = getUserId();

		termCacheModel.userName = getUserName();

		String userName = termCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			termCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			termCacheModel.createDate = createDate.getTime();
		}
		else {
			termCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			termCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			termCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return termCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Term, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Term, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Term, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Term)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Term, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Term, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Term, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Term)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Term>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _termId;
	private long _parentId;
	private String _languageId;
	private String _prefix;
	private String _originalPrefix;
	private String _year;
	private String _originalYear;
	private String _translation;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _columnBitmask;
	private Term _escapedModel;

}