/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import de.uhh.l2g.plugins.model.Video_Category;
import de.uhh.l2g.plugins.model.Video_CategoryModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Video_Category service. Represents a row in the &quot;LG_Video_Category&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>Video_CategoryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Video_CategoryImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Video_CategoryImpl
 * @generated
 */
@ProviderType
public class Video_CategoryModelImpl
	extends BaseModelImpl<Video_Category> implements Video_CategoryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a video_ category model instance should use the <code>Video_Category</code> interface instead.
	 */
	public static final String TABLE_NAME = "LG_Video_Category";

	public static final Object[][] TABLE_COLUMNS = {
		{"videoCategoryId", Types.BIGINT}, {"videoId", Types.BIGINT},
		{"categoryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("videoCategoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("videoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("categoryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LG_Video_Category (videoCategoryId LONG not null primary key,videoId LONG,categoryId LONG)";

	public static final String TABLE_SQL_DROP = "drop table LG_Video_Category";

	public static final String ORDER_BY_JPQL =
		" ORDER BY video_Category.videoCategoryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LG_Video_Category.videoCategoryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.Video_Category"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.Video_Category"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.de.uhh.l2g.plugins.model.Video_Category"),
		true);

	public static final long CATEGORYID_COLUMN_BITMASK = 1L;

	public static final long VIDEOID_COLUMN_BITMASK = 2L;

	public static final long VIDEOCATEGORYID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"lock.expiration.time.de.uhh.l2g.plugins.model.Video_Category"));

	public Video_CategoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _videoCategoryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVideoCategoryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _videoCategoryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Video_Category.class;
	}

	@Override
	public String getModelClassName() {
		return Video_Category.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Video_Category, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Video_Category, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Video_Category, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Video_Category)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Video_Category, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Video_Category, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Video_Category)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Video_Category, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Video_Category, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Video_Category>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Video_Category.class.getClassLoader(), Video_Category.class,
			ModelWrapper.class);

		try {
			Constructor<Video_Category> constructor =
				(Constructor<Video_Category>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Video_Category, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Video_Category, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Video_Category, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Video_Category, Object>>();
		Map<String, BiConsumer<Video_Category, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Video_Category, ?>>();

		attributeGetterFunctions.put(
			"videoCategoryId", Video_Category::getVideoCategoryId);
		attributeSetterBiConsumers.put(
			"videoCategoryId",
			(BiConsumer<Video_Category, Long>)
				Video_Category::setVideoCategoryId);
		attributeGetterFunctions.put("videoId", Video_Category::getVideoId);
		attributeSetterBiConsumers.put(
			"videoId",
			(BiConsumer<Video_Category, Long>)Video_Category::setVideoId);
		attributeGetterFunctions.put(
			"categoryId", Video_Category::getCategoryId);
		attributeSetterBiConsumers.put(
			"categoryId",
			(BiConsumer<Video_Category, Long>)Video_Category::setCategoryId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getVideoCategoryId() {
		return _videoCategoryId;
	}

	@Override
	public void setVideoCategoryId(long videoCategoryId) {
		_videoCategoryId = videoCategoryId;
	}

	@Override
	public long getVideoId() {
		return _videoId;
	}

	@Override
	public void setVideoId(long videoId) {
		_columnBitmask |= VIDEOID_COLUMN_BITMASK;

		if (!_setOriginalVideoId) {
			_setOriginalVideoId = true;

			_originalVideoId = _videoId;
		}

		_videoId = videoId;
	}

	public long getOriginalVideoId() {
		return _originalVideoId;
	}

	@Override
	public long getCategoryId() {
		return _categoryId;
	}

	@Override
	public void setCategoryId(long categoryId) {
		_columnBitmask |= CATEGORYID_COLUMN_BITMASK;

		if (!_setOriginalCategoryId) {
			_setOriginalCategoryId = true;

			_originalCategoryId = _categoryId;
		}

		_categoryId = categoryId;
	}

	public long getOriginalCategoryId() {
		return _originalCategoryId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Video_Category.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Video_Category toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Video_Category>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Video_CategoryImpl video_CategoryImpl = new Video_CategoryImpl();

		video_CategoryImpl.setVideoCategoryId(getVideoCategoryId());
		video_CategoryImpl.setVideoId(getVideoId());
		video_CategoryImpl.setCategoryId(getCategoryId());

		video_CategoryImpl.resetOriginalValues();

		return video_CategoryImpl;
	}

	@Override
	public int compareTo(Video_Category video_Category) {
		long primaryKey = video_Category.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Video_Category)) {
			return false;
		}

		Video_Category video_Category = (Video_Category)obj;

		long primaryKey = video_Category.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		Video_CategoryModelImpl video_CategoryModelImpl = this;

		video_CategoryModelImpl._originalVideoId =
			video_CategoryModelImpl._videoId;

		video_CategoryModelImpl._setOriginalVideoId = false;

		video_CategoryModelImpl._originalCategoryId =
			video_CategoryModelImpl._categoryId;

		video_CategoryModelImpl._setOriginalCategoryId = false;

		video_CategoryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Video_Category> toCacheModel() {
		Video_CategoryCacheModel video_CategoryCacheModel =
			new Video_CategoryCacheModel();

		video_CategoryCacheModel.videoCategoryId = getVideoCategoryId();

		video_CategoryCacheModel.videoId = getVideoId();

		video_CategoryCacheModel.categoryId = getCategoryId();

		return video_CategoryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Video_Category, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Video_Category, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Video_Category, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Video_Category)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Video_Category, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Video_Category, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Video_Category, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Video_Category)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Video_Category>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _videoCategoryId;
	private long _videoId;
	private long _originalVideoId;
	private boolean _setOriginalVideoId;
	private long _categoryId;
	private long _originalCategoryId;
	private boolean _setOriginalCategoryId;
	private long _columnBitmask;
	private Video_Category _escapedModel;

}