/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import de.uhh.l2g.plugins.model.Video_MediaType;
import de.uhh.l2g.plugins.model.Video_MediaTypeModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Video_MediaType service. Represents a row in the &quot;LG_Video_MediaType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>Video_MediaTypeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Video_MediaTypeImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Video_MediaTypeImpl
 * @generated
 */
public class Video_MediaTypeModelImpl
	extends BaseModelImpl<Video_MediaType> implements Video_MediaTypeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a video_ media type model instance should use the <code>Video_MediaType</code> interface instead.
	 */
	public static final String TABLE_NAME = "LG_Video_MediaType";

	public static final Object[][] TABLE_COLUMNS = {
		{"videoMediaTypeId", Types.BIGINT}, {"videoId", Types.BIGINT},
		{"MediaTypeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("videoMediaTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("videoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("MediaTypeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LG_Video_MediaType (videoMediaTypeId LONG not null primary key,videoId LONG,MediaTypeId LONG)";

	public static final String TABLE_SQL_DROP = "drop table LG_Video_MediaType";

	public static final String ORDER_BY_JPQL =
		" ORDER BY video_MediaType.videoMediaTypeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LG_Video_MediaType.videoMediaTypeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.Video_MediaType"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.Video_MediaType"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.de.uhh.l2g.plugins.model.Video_MediaType"),
		true);

	public static final long MEDIATYPEID_COLUMN_BITMASK = 1L;

	public static final long VIDEOID_COLUMN_BITMASK = 2L;

	public static final long VIDEOMEDIATYPEID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		de.uhh.l2g.plugins.service.util.ServiceProps.get(
			"lock.expiration.time.de.uhh.l2g.plugins.model.Video_MediaType"));

	public Video_MediaTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _videoMediaTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVideoMediaTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _videoMediaTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Video_MediaType.class;
	}

	@Override
	public String getModelClassName() {
		return Video_MediaType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Video_MediaType, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Video_MediaType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Video_MediaType, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Video_MediaType)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Video_MediaType, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Video_MediaType, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Video_MediaType)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Video_MediaType, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Video_MediaType, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Video_MediaType>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Video_MediaType.class.getClassLoader(), Video_MediaType.class,
			ModelWrapper.class);

		try {
			Constructor<Video_MediaType> constructor =
				(Constructor<Video_MediaType>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Video_MediaType, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Video_MediaType, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Video_MediaType, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<Video_MediaType, Object>>();
		Map<String, BiConsumer<Video_MediaType, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Video_MediaType, ?>>();

		attributeGetterFunctions.put(
			"videoMediaTypeId", Video_MediaType::getVideoMediaTypeId);
		attributeSetterBiConsumers.put(
			"videoMediaTypeId",
			(BiConsumer<Video_MediaType, Long>)
				Video_MediaType::setVideoMediaTypeId);
		attributeGetterFunctions.put("videoId", Video_MediaType::getVideoId);
		attributeSetterBiConsumers.put(
			"videoId",
			(BiConsumer<Video_MediaType, Long>)Video_MediaType::setVideoId);
		attributeGetterFunctions.put(
			"MediaTypeId", Video_MediaType::getMediaTypeId);
		attributeSetterBiConsumers.put(
			"MediaTypeId",
			(BiConsumer<Video_MediaType, Long>)Video_MediaType::setMediaTypeId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getVideoMediaTypeId() {
		return _videoMediaTypeId;
	}

	@Override
	public void setVideoMediaTypeId(long videoMediaTypeId) {
		_videoMediaTypeId = videoMediaTypeId;
	}

	@Override
	public long getVideoId() {
		return _videoId;
	}

	@Override
	public void setVideoId(long videoId) {
		_columnBitmask |= VIDEOID_COLUMN_BITMASK;

		if (!_setOriginalVideoId) {
			_setOriginalVideoId = true;

			_originalVideoId = _videoId;
		}

		_videoId = videoId;
	}

	public long getOriginalVideoId() {
		return _originalVideoId;
	}

	@Override
	public long getMediaTypeId() {
		return _MediaTypeId;
	}

	@Override
	public void setMediaTypeId(long MediaTypeId) {
		_columnBitmask |= MEDIATYPEID_COLUMN_BITMASK;

		if (!_setOriginalMediaTypeId) {
			_setOriginalMediaTypeId = true;

			_originalMediaTypeId = _MediaTypeId;
		}

		_MediaTypeId = MediaTypeId;
	}

	public long getOriginalMediaTypeId() {
		return _originalMediaTypeId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Video_MediaType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Video_MediaType toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Video_MediaType>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Video_MediaTypeImpl video_MediaTypeImpl = new Video_MediaTypeImpl();

		video_MediaTypeImpl.setVideoMediaTypeId(getVideoMediaTypeId());
		video_MediaTypeImpl.setVideoId(getVideoId());
		video_MediaTypeImpl.setMediaTypeId(getMediaTypeId());

		video_MediaTypeImpl.resetOriginalValues();

		return video_MediaTypeImpl;
	}

	@Override
	public int compareTo(Video_MediaType video_MediaType) {
		long primaryKey = video_MediaType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Video_MediaType)) {
			return false;
		}

		Video_MediaType video_MediaType = (Video_MediaType)object;

		long primaryKey = video_MediaType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		Video_MediaTypeModelImpl video_MediaTypeModelImpl = this;

		video_MediaTypeModelImpl._originalVideoId =
			video_MediaTypeModelImpl._videoId;

		video_MediaTypeModelImpl._setOriginalVideoId = false;

		video_MediaTypeModelImpl._originalMediaTypeId =
			video_MediaTypeModelImpl._MediaTypeId;

		video_MediaTypeModelImpl._setOriginalMediaTypeId = false;

		video_MediaTypeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Video_MediaType> toCacheModel() {
		Video_MediaTypeCacheModel video_MediaTypeCacheModel =
			new Video_MediaTypeCacheModel();

		video_MediaTypeCacheModel.videoMediaTypeId = getVideoMediaTypeId();

		video_MediaTypeCacheModel.videoId = getVideoId();

		video_MediaTypeCacheModel.MediaTypeId = getMediaTypeId();

		return video_MediaTypeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Video_MediaType, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Video_MediaType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Video_MediaType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Video_MediaType)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Video_MediaType, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Video_MediaType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Video_MediaType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Video_MediaType)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Video_MediaType>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _videoMediaTypeId;
	private long _videoId;
	private long _originalVideoId;
	private boolean _setOriginalVideoId;
	private long _MediaTypeId;
	private long _originalMediaTypeId;
	private boolean _setOriginalMediaTypeId;
	private long _columnBitmask;
	private Video_MediaType _escapedModel;

}