/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import de.uhh.l2g.plugins.model.Video_Creator;
import de.uhh.l2g.plugins.service.Video_CreatorLocalServiceUtil;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The extended model base implementation for the Video_Creator service. Represents a row in the &quot;LG_Video_Creator&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Video_CreatorImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Video_CreatorImpl
 * @see Video_Creator
 * @generated
 */
@ProviderType
public abstract class Video_CreatorBaseImpl
	extends Video_CreatorModelImpl implements Video_Creator {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a video_ creator model instance should use the <code>Video_Creator</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Video_CreatorLocalServiceUtil.addVideo_Creator(this);
		}
		else {
			Video_CreatorLocalServiceUtil.updateVideo_Creator(this);
		}
	}

}