/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import de.uhh.l2g.plugins.model.Videohitlist;
import de.uhh.l2g.plugins.service.VideohitlistLocalServiceUtil;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The extended model base implementation for the Videohitlist service. Represents a row in the &quot;LG_Videohitlist&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VideohitlistImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see VideohitlistImpl
 * @see Videohitlist
 * @generated
 */
@ProviderType
public abstract class VideohitlistBaseImpl
	extends VideohitlistModelImpl implements Videohitlist {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a videohitlist model instance should use the <code>Videohitlist</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			VideohitlistLocalServiceUtil.addVideohitlist(this);
		}
		else {
			VideohitlistLocalServiceUtil.updateVideohitlist(this);
		}
	}

}