/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Creator service. Represents a row in the &quot;LG_Creator&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>de.uhh.l2g.plugins.model.impl.CreatorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>de.uhh.l2g.plugins.model.impl.CreatorImpl</code>.
 * </p>
 *
 * @author Iavor Sturm
 * @see Creator
 * @generated
 */
@ProviderType
public interface CreatorModel
	extends BaseModel<Creator>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a creator model instance should use the {@link Creator} interface instead.
	 */

	/**
	 * Returns the primary key of this creator.
	 *
	 * @return the primary key of this creator
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this creator.
	 *
	 * @param primaryKey the primary key of this creator
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the creator ID of this creator.
	 *
	 * @return the creator ID of this creator
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this creator.
	 *
	 * @param creatorId the creator ID of this creator
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the first name of this creator.
	 *
	 * @return the first name of this creator
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this creator.
	 *
	 * @param firstName the first name of this creator
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this creator.
	 *
	 * @return the last name of this creator
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this creator.
	 *
	 * @param lastName the last name of this creator
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the middle name of this creator.
	 *
	 * @return the middle name of this creator
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this creator.
	 *
	 * @param middleName the middle name of this creator
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the job title of this creator.
	 *
	 * @return the job title of this creator
	 */
	@AutoEscape
	public String getJobTitle();

	/**
	 * Sets the job title of this creator.
	 *
	 * @param jobTitle the job title of this creator
	 */
	public void setJobTitle(String jobTitle);

	/**
	 * Returns the gender of this creator.
	 *
	 * @return the gender of this creator
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this creator.
	 *
	 * @param gender the gender of this creator
	 */
	public void setGender(String gender);

	/**
	 * Returns the full name of this creator.
	 *
	 * @return the full name of this creator
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this creator.
	 *
	 * @param fullName the full name of this creator
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the group ID of this creator.
	 *
	 * @return the group ID of this creator
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this creator.
	 *
	 * @param groupId the group ID of this creator
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this creator.
	 *
	 * @return the company ID of this creator
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this creator.
	 *
	 * @param companyId the company ID of this creator
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this creator.
	 *
	 * @return the user ID of this creator
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this creator.
	 *
	 * @param userId the user ID of this creator
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this creator.
	 *
	 * @return the user uuid of this creator
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this creator.
	 *
	 * @param userUuid the user uuid of this creator
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this creator.
	 *
	 * @return the user name of this creator
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this creator.
	 *
	 * @param userName the user name of this creator
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this creator.
	 *
	 * @return the create date of this creator
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this creator.
	 *
	 * @param createDate the create date of this creator
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this creator.
	 *
	 * @return the modified date of this creator
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this creator.
	 *
	 * @param modifiedDate the modified date of this creator
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}