/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MediaType service. Represents a row in the &quot;LG_MediaType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>de.uhh.l2g.plugins.model.impl.MediaTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>de.uhh.l2g.plugins.model.impl.MediaTypeImpl</code>.
 * </p>
 *
 * @author Iavor Sturm
 * @see MediaType
 * @generated
 */
@ProviderType
public interface MediaTypeModel
	extends BaseModel<MediaType>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a media type model instance should use the {@link MediaType} interface instead.
	 */

	/**
	 * Returns the primary key of this media type.
	 *
	 * @return the primary key of this media type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this media type.
	 *
	 * @param primaryKey the primary key of this media type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the media type ID of this media type.
	 *
	 * @return the media type ID of this media type
	 */
	public long getMediaTypeId();

	/**
	 * Sets the media type ID of this media type.
	 *
	 * @param mediaTypeId the media type ID of this media type
	 */
	public void setMediaTypeId(long mediaTypeId);

	/**
	 * Returns the media type name of this media type.
	 *
	 * @return the media type name of this media type
	 */
	@AutoEscape
	public String getMediaTypeName();

	/**
	 * Sets the media type name of this media type.
	 *
	 * @param mediaTypeName the media type name of this media type
	 */
	public void setMediaTypeName(String mediaTypeName);

	/**
	 * Returns the group ID of this media type.
	 *
	 * @return the group ID of this media type
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this media type.
	 *
	 * @param groupId the group ID of this media type
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this media type.
	 *
	 * @return the company ID of this media type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this media type.
	 *
	 * @param companyId the company ID of this media type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this media type.
	 *
	 * @return the user ID of this media type
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this media type.
	 *
	 * @param userId the user ID of this media type
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this media type.
	 *
	 * @return the user uuid of this media type
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this media type.
	 *
	 * @param userUuid the user uuid of this media type
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this media type.
	 *
	 * @return the user name of this media type
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this media type.
	 *
	 * @param userName the user name of this media type
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this media type.
	 *
	 * @return the create date of this media type
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this media type.
	 *
	 * @param createDate the create date of this media type
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this media type.
	 *
	 * @return the modified date of this media type
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this media type.
	 *
	 * @param modifiedDate the modified date of this media type
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}