/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the OaiSet service. Represents a row in the &quot;LG_OaiSet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>de.uhh.l2g.plugins.model.impl.OaiSetModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>de.uhh.l2g.plugins.model.impl.OaiSetImpl</code>.
 * </p>
 *
 * @author Iavor Sturm
 * @see OaiSet
 * @generated
 */
@ProviderType
public interface OaiSetModel extends BaseModel<OaiSet> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a oai set model instance should use the {@link OaiSet} interface instead.
	 */

	/**
	 * Returns the primary key of this oai set.
	 *
	 * @return the primary key of this oai set
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this oai set.
	 *
	 * @param primaryKey the primary key of this oai set
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the oai set ID of this oai set.
	 *
	 * @return the oai set ID of this oai set
	 */
	public long getOaiSetId();

	/**
	 * Sets the oai set ID of this oai set.
	 *
	 * @param oaiSetId the oai set ID of this oai set
	 */
	public void setOaiSetId(long oaiSetId);

	/**
	 * Returns the set spec of this oai set.
	 *
	 * @return the set spec of this oai set
	 */
	@AutoEscape
	public String getSetSpec();

	/**
	 * Sets the set spec of this oai set.
	 *
	 * @param setSpec the set spec of this oai set
	 */
	public void setSetSpec(String setSpec);

	/**
	 * Returns the set name of this oai set.
	 *
	 * @return the set name of this oai set
	 */
	@AutoEscape
	public String getSetName();

	/**
	 * Sets the set name of this oai set.
	 *
	 * @param setName the set name of this oai set
	 */
	public void setSetName(String setName);

	/**
	 * Returns the set description of this oai set.
	 *
	 * @return the set description of this oai set
	 */
	@AutoEscape
	public String getSetDescription();

	/**
	 * Sets the set description of this oai set.
	 *
	 * @param setDescription the set description of this oai set
	 */
	public void setSetDescription(String setDescription);

}