/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Video_Institution service. Represents a row in the &quot;LG_Video_Institution&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>de.uhh.l2g.plugins.model.impl.Video_InstitutionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>de.uhh.l2g.plugins.model.impl.Video_InstitutionImpl</code>.
 * </p>
 *
 * @author Iavor Sturm
 * @see Video_Institution
 * @generated
 */
@ProviderType
public interface Video_InstitutionModel extends BaseModel<Video_Institution> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a video_ institution model instance should use the {@link Video_Institution} interface instead.
	 */

	/**
	 * Returns the primary key of this video_ institution.
	 *
	 * @return the primary key of this video_ institution
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this video_ institution.
	 *
	 * @param primaryKey the primary key of this video_ institution
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the video institution ID of this video_ institution.
	 *
	 * @return the video institution ID of this video_ institution
	 */
	public long getVideoInstitutionId();

	/**
	 * Sets the video institution ID of this video_ institution.
	 *
	 * @param videoInstitutionId the video institution ID of this video_ institution
	 */
	public void setVideoInstitutionId(long videoInstitutionId);

	/**
	 * Returns the video ID of this video_ institution.
	 *
	 * @return the video ID of this video_ institution
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this video_ institution.
	 *
	 * @param videoId the video ID of this video_ institution
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the institution ID of this video_ institution.
	 *
	 * @return the institution ID of this video_ institution
	 */
	public long getInstitutionId();

	/**
	 * Sets the institution ID of this video_ institution.
	 *
	 * @param institutionId the institution ID of this video_ institution
	 */
	public void setInstitutionId(long institutionId);

	/**
	 * Returns the institution parent ID of this video_ institution.
	 *
	 * @return the institution parent ID of this video_ institution
	 */
	public long getInstitutionParentId();

	/**
	 * Sets the institution parent ID of this video_ institution.
	 *
	 * @param institutionParentId the institution parent ID of this video_ institution
	 */
	public void setInstitutionParentId(long institutionParentId);

}