/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Videohitlist service. Represents a row in the &quot;LG_Videohitlist&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>de.uhh.l2g.plugins.model.impl.VideohitlistModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>de.uhh.l2g.plugins.model.impl.VideohitlistImpl</code>.
 * </p>
 *
 * @author Iavor Sturm
 * @see Videohitlist
 * @generated
 */
@ProviderType
public interface VideohitlistModel
	extends BaseModel<Videohitlist>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a videohitlist model instance should use the {@link Videohitlist} interface instead.
	 */

	/**
	 * Returns the primary key of this videohitlist.
	 *
	 * @return the primary key of this videohitlist
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this videohitlist.
	 *
	 * @param primaryKey the primary key of this videohitlist
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the videohitlist ID of this videohitlist.
	 *
	 * @return the videohitlist ID of this videohitlist
	 */
	public long getVideohitlistId();

	/**
	 * Sets the videohitlist ID of this videohitlist.
	 *
	 * @param videohitlistId the videohitlist ID of this videohitlist
	 */
	public void setVideohitlistId(long videohitlistId);

	/**
	 * Returns the hits per day of this videohitlist.
	 *
	 * @return the hits per day of this videohitlist
	 */
	public long getHitsPerDay();

	/**
	 * Sets the hits per day of this videohitlist.
	 *
	 * @param hitsPerDay the hits per day of this videohitlist
	 */
	public void setHitsPerDay(long hitsPerDay);

	/**
	 * Returns the hits per week of this videohitlist.
	 *
	 * @return the hits per week of this videohitlist
	 */
	public long getHitsPerWeek();

	/**
	 * Sets the hits per week of this videohitlist.
	 *
	 * @param hitsPerWeek the hits per week of this videohitlist
	 */
	public void setHitsPerWeek(long hitsPerWeek);

	/**
	 * Returns the hits per month of this videohitlist.
	 *
	 * @return the hits per month of this videohitlist
	 */
	public long getHitsPerMonth();

	/**
	 * Sets the hits per month of this videohitlist.
	 *
	 * @param hitsPerMonth the hits per month of this videohitlist
	 */
	public void setHitsPerMonth(long hitsPerMonth);

	/**
	 * Returns the hits per year of this videohitlist.
	 *
	 * @return the hits per year of this videohitlist
	 */
	public long getHitsPerYear();

	/**
	 * Sets the hits per year of this videohitlist.
	 *
	 * @param hitsPerYear the hits per year of this videohitlist
	 */
	public void setHitsPerYear(long hitsPerYear);

	/**
	 * Returns the video ID of this videohitlist.
	 *
	 * @return the video ID of this videohitlist
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this videohitlist.
	 *
	 * @param videoId the video ID of this videohitlist
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the group ID of this videohitlist.
	 *
	 * @return the group ID of this videohitlist
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this videohitlist.
	 *
	 * @param groupId the group ID of this videohitlist
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this videohitlist.
	 *
	 * @return the company ID of this videohitlist
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this videohitlist.
	 *
	 * @param companyId the company ID of this videohitlist
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this videohitlist.
	 *
	 * @return the user ID of this videohitlist
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this videohitlist.
	 *
	 * @param userId the user ID of this videohitlist
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this videohitlist.
	 *
	 * @return the user uuid of this videohitlist
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this videohitlist.
	 *
	 * @param userUuid the user uuid of this videohitlist
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this videohitlist.
	 *
	 * @return the user name of this videohitlist
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this videohitlist.
	 *
	 * @param userName the user name of this videohitlist
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this videohitlist.
	 *
	 * @return the create date of this videohitlist
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this videohitlist.
	 *
	 * @param createDate the create date of this videohitlist
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this videohitlist.
	 *
	 * @return the modified date of this videohitlist
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this videohitlist.
	 *
	 * @param modifiedDate the modified date of this videohitlist
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}