/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Video_Category service. Represents a row in the &quot;LG_Video_Category&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>de.uhh.l2g.plugins.model.impl.Video_CategoryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>de.uhh.l2g.plugins.model.impl.Video_CategoryImpl</code>.
 * </p>
 *
 * @author Iavor Sturm
 * @see Video_Category
 * @generated
 */
@ProviderType
public interface Video_CategoryModel extends BaseModel<Video_Category> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a video_ category model instance should use the {@link Video_Category} interface instead.
	 */

	/**
	 * Returns the primary key of this video_ category.
	 *
	 * @return the primary key of this video_ category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this video_ category.
	 *
	 * @param primaryKey the primary key of this video_ category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the video category ID of this video_ category.
	 *
	 * @return the video category ID of this video_ category
	 */
	public long getVideoCategoryId();

	/**
	 * Sets the video category ID of this video_ category.
	 *
	 * @param videoCategoryId the video category ID of this video_ category
	 */
	public void setVideoCategoryId(long videoCategoryId);

	/**
	 * Returns the video ID of this video_ category.
	 *
	 * @return the video ID of this video_ category
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this video_ category.
	 *
	 * @param videoId the video ID of this video_ category
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the category ID of this video_ category.
	 *
	 * @return the category ID of this video_ category
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this video_ category.
	 *
	 * @param categoryId the category ID of this video_ category
	 */
	public void setCategoryId(long categoryId);

}